version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: mediccenter-postgres
    environment:
      POSTGRES_DB: medic_center
      POSTGRES_USER: user_medic
      POSTGRES_PASSWORD: password_medic
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_medic -d medic_center"]
      interval: 5s
      timeout: 5s
      retries: 5

  insurance-mock:
    build:
      context: ./insurance-validation-mock-service
    container_name: insurance-mock-service
    ports:
      - "8081:8081"

  medic-center-app:
    build:
      context: .
    container_name: medic-center-application
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/medic_center
      - SPRING_DATASOURCE_USERNAME=user_medic
      - SPRING_DATASOURCE_PASSWORD=password_medic
      - INSURANCE_VALIDATION_URL=http://insurance-mock:8081/coverage-evaluation
    depends_on:
      postgres-db:
        condition: service_healthy
      insurance-mock:
        condition: service_started

volumes:
  postgres_data:
