version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: mediccenter-postgres
    environment:
      POSTGRES_DB: medic_center
      POSTGRES_USER: user_medic
      POSTGRES_PASSWORD: password_medic
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
